name: Test

on:
  push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm install -g @quasar/cli
      - run: quasar build
      - run: npm run test:e2e:ci
      - run: npm run test:unit:ci